version: "3"
services:
  server:
    image: openphotos-server
    container_name: openphotos-server
    restart: unless-stopped
    build:
      context: ./server
      args:
        PORT: ${SERVER_PORT}
    ports:
      - "${SERVER_PORT}:8081"
    depends_on:
      - mongo
    volumes:
      - ./server/config:/usr/src/app/config
      - ./server/data:/usr/src/app/data
  client:
    image: openphotos-client
    container_name: openphotos-client
    restart: unless-stopped
    build:
      context: ./client
      args:
        PORT: ${CLIENT_PORT}
    ports:
      - "${CLIENT_PORT}:8080"
  mongo:
    container_name: openphotos-db
    restart: unless-stopped
    image: mongo
    volumes:
      - openphotos-data:/data/db

volumes:
  openphotos-data: